before_install:
 - sudo apt-get update -qq
 - sudo apt-get install git build-essential python3-dev libmysqlclient-dev

language: python

python: 
  - "3.4"

install: 
  - sudo pip install -r requirements.txt
  - python manage.py configure
  - python manage.py content create

script: 
  - python manage.py test all