before_install:
 - sudo apt-get update -qq
 - sudo apt-get install git build-essential python3-dev libmysqlclient-dev

language: python

python: 
  - 3.4

install: 
  - sudo pip3 install -r requirements.txt
  - python3 manage.py configure
  - python3 manage.py content create

script: 
  - python3 manage.py test all