before_install:
	- sudo apt-get update -qq
	- sudo apt-get install install git python3-setuptools build-essential python3-dev libmysqlclient-dev python3-pip
	

language: python

python: 
	- "3.4"

install: 
	- sudo pip install -r requirements.txt
	- python manage.py configure

script: 
	- python manage.py test all